/*
 * Copyright (C) 2015-2016 Daniel Schwierzeck, daniel.schwierzeck@gmail.com
 *
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * Common board configuration for Lantiq XWAY xRX330 family
 */

#ifndef __XRX330_CONFIG_H__
#define __XRX330_CONFIG_H__

/* CPU and SoC type */
#define CONFIG_SOC_LANTIQ
#define CONFIG_SOC_XWAY_XRX330

/* Cache configuration */
#define CONFIG_SYS_MIPS_CACHE_MODE	CONF_CM_CACHABLE_NONCOHERENT
#define CONFIG_SYS_MIPS_CACHE_BASE	0x9fc00000
#define CONFIG_SYS_MIPS_CACHE_INIT_RAM_LOAD

#define CONFIG_SYS_MALLOC_LEN		6 * 1024 * 1024

/*
 * Supported clock modes
 */
#define LTQ_CLK_CPU_720_DDR_360		0
#define LTQ_CLK_CPU_600_DDR_300		1
#define LTQ_CLK_CPU_300_DDR_300		2
#define LTQ_CLK_CPU_300_DDR_150		3
#define LTQ_CLK_CPU_150_DDR_150		4

/* CPU speed */
#ifndef CONFIG_SYS_CLOCK_MODE
#define CONFIG_SYS_CLOCK_MODE		LTQ_CLK_CPU_600_DDR_300
#endif
#define CONFIG_SYS_HZ			1000

/* RAM */
#define CONFIG_SYS_SDRAM_BASE		0x80000000
#define CONFIG_SYS_SDRAM_BASE_UC	0xa0000000
#define CONFIG_SYS_MEMTEST_START	0x81000000
#define CONFIG_SYS_MEMTEST_END		0x82000000
#define CONFIG_SYS_LOAD_ADDR		0x81000000
#define CONFIG_SYS_LOAD_SIZE		(2 * 1024 * 1024)
#define CONFIG_SYS_INIT_SP_OFFSET	(32 * 1024)

/* SRAM */
#define CONFIG_SYS_SRAM_BASE		0xBE1A0000
#define CONFIG_SYS_SRAM_SIZE		0x10000

/* ASC/UART driver and console */
#define CONFIG_LANTIQ_SERIAL
#define CONFIG_SYS_BAUDRATE_TABLE	{ 9600, 19200, 38400, 57600, 115200 }

/* GPIO */
#define CONFIG_LANTIQ_GPIO
#define CONFIG_LTQ_GPIO_MAX_BANKS	3
#define CONFIG_LTQ_HAS_GPIO_BANK3

/* FLASH driver */
#define CONFIG_SYS_NO_FLASH

#if defined(CONFIG_LTQ_SUPPORT_SPI_FLASH)
#define CONFIG_LANTIQ_SPI
#define CONFIG_SPI_FLASH

#define CONFIG_CMD_SF
#define CONFIG_CMD_SPI
#endif

#if defined(CONFIG_LTQ_SUPPORT_HSNAND_FLASH)
#define CONFIG_NAND_LANTIQ_HSNAND
#define CONFIG_SYS_NAND_ONFI_DETECTION
#define CONFIG_SYS_NAND_SELF_INIT
#define CONFIG_SYS_MAX_NAND_DEVICE	1
#define CONFIG_SYS_NAND_BASE0		0xB0000000
#define CONFIG_SYS_NAND_BASE1		0xB4000000

#if defined(CONFIG_LTQ_NAND_CS0)
#define CONFIG_SYS_NAND_BASE		(CONFIG_SYS_NAND_BASE0)
#elif defined(CONFIG_LTQ_NAND_CS1)
#define CONFIG_SYS_NAND_BASE		(CONFIG_SYS_NAND_BASE1)
#else
#error "invalid NAND configuration"
#endif

#define CONFIG_CMD_NAND
#endif

#if defined(CONFIG_LTQ_SUPPORT_ETHERNET)
#define CONFIG_LANTIQ_DMA
#define CONFIG_LANTIQ_XRX300_SWITCH
#define CONFIG_PHY_LANTIQ

#define CONFIG_SYS_RX_ETH_BUFFER	8
#define CONFIG_PHYLIB
#define CONFIG_MII
#define CONFIG_UDP_CHECKSUM

#define CONFIG_CMD_MII
#define CONFIG_CMD_NET

#define CONFIG_FW_LOADER
#endif

#define CONFIG_SPL_MAX_SIZE		(32 * 1024)
#define CONFIG_SPL_BSS_SIZE		(4 * 1024)
#define CONFIG_SPL_STACK_SIZE		(4 * 1024)
#define CONFIG_SPL_STACK_BASE		(CONFIG_SYS_SRAM_BASE + \
					CONFIG_SPL_MAX_SIZE + \
					CONFIG_SPL_STACK_SIZE - 1)
#define CONFIG_SPL_BSS_BASE		(CONFIG_SPL_STACK_BASE + 1)

#define CONFIG_SPL_MC_TUNE_BASE		(CONFIG_SYS_SDRAM_BASE_UC + \
					CONFIG_SYS_INIT_SP_OFFSET)

#if defined(CONFIG_SYS_BOOT_RAM)
#define CONFIG_SYS_TEXT_BASE		0xA0100000
#define CONFIG_SKIP_LOWLEVEL_INIT
#define CONFIG_SYS_DISABLE_CACHE
#endif

#if defined(CONFIG_SYS_BOOT_SFSPL) || defined(CONFIG_SYS_BOOT_NANDHWSPL)
#define CONFIG_SYS_TEXT_BASE		0x80100000
#define CONFIG_SPL_TEXT_BASE		0xBE1A0000
#endif

#if defined(CONFIG_SYS_BOOT_NANDSPL)
#define CONFIG_SYS_TEXT_BASE		0x80100000
#if defined(CONFIG_TPL_BUILD)
#define CONFIG_SPL_TEXT_BASE		0xBE1A0800
#else
#define CONFIG_SPL_TEXT_BASE		0xBE1A0000
#endif
#define CONFIG_TPL_TEXT_BASE		0xBE1A0800
#endif

#define	CONFIG_SYS_MONITOR_BASE		CONFIG_SYS_TEXT_BASE

#endif /* __XRX330_CONFIG_H__ */
