#
# Copyright (C) 2011-2013 Daniel Schwierzeck, daniel.schwierzeck@gmail.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SWITCH_MULTI) += switch.o
obj-$(CONFIG_SWITCH_PSB697X) += psb697x.o
obj-$(CONFIG_SWITCH_ADM6996I) += adm6996i.o
obj-$(CONFIG_SWITCH_AR8216) += ar8216.o
